In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/processed/telco_customer_churn_cleaned.csv")

In [3]:
df.head()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,LTV
0,7590-VHVEG,Female,No,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,29.85
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,1936.30
2,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,107.70
3,7795-CFOCW,Male,No,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1903.50
4,9237-HQITU,Female,No,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,141.40

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        7043 non-null   str
 1   Gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   str
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   Tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   str
 21  LTV               7043 non-null   float64
dtypes: float64(3), int64(1), str(18)
memory usage: 1.2 MB

In [5]:
df.shape

(7043, 22)

In [6]:
df.isnull().sum()

CustomerID          0
Gender              0
SeniorCitizen       0
Partner             0
Dependents          0
Tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
LTV                 0
dtype: int64

In [7]:
df.columns

Index(['CustomerID', 'Gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'Tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn', 'LTV'],
      dtype='str')

In [8]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [9]:
df.nunique()

CustomerID          7043
Gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
Tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
LTV                 6018
dtype: int64

**1. ANNUAL CHARGES**

In [14]:
df['AnnualCharges']=df['MonthlyCharges']*12

In [15]:
df.head()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,LTV,AnnualCharges
0,7590-VHVEG,Female,No,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,29.85,358.2
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.50,No,1936.30,683.4
2,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,107.70,646.2
3,7795-CFOCW,Male,No,No,No,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1903.50,507.6
4,9237-HQITU,Female,No,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,141.40,848.4

**2. TENURE GROUP**

In [20]:
df["TenureGroup"] = pd.cut(
    df["Tenure"],
    bins=[-1, 12, 24, 48, 72],
    labels=[
        "0-12 months",
        "13-24 months",
        "25-48 months",
        "49-72 months"
    ]
)

**3. IS MONTH TO MONTH**
( This feature identifies customers who are on month-to-month contracts.Month-to-month customers have a higher churn rate. )

In [27]:
df['IsMonthToMonth']=(df['Contract']=='Month-to-month').astype(int)

In [35]:
df[['IsMonthToMonth','Contract']].head(10)

   IsMonthToMonth        Contract
0               1  Month-to-month
1               0        One year
2               1  Month-to-month
3               0        One year
4               1  Month-to-month
5               1  Month-to-month
6               1  Month-to-month
7               1  Month-to-month
8               1  Month-to-month
9               0        One year

**=> reviewing new columns**

In [41]:
df[
    [
        "Tenure",
        "TenureGroup",
        "MonthlyCharges",
        "AnnualCharges",
        "Contract",
        "IsMonthToMonth"
    ]
].head(10)

,Tenure,TenureGroup,MonthlyCharges,AnnualCharges,Contract,IsMonthToMonth
0,1,0-12 months,29.85,358.2,Month-to-month,1
1,34,25-48 months,56.95,683.4,One year,0
2,2,0-12 months,53.85,646.2,Month-to-month,1
3,45,25-48 months,42.30,507.6,One year,0
4,2,0-12 months,70.70,848.4,Month-to-month,1
5,8,0-12 months,99.65,1195.8,Month-to-month,1
6,22,13-24 months,89.10,1069.2,Month-to-month,1
7,10,0-12 months,29.75,357.0,Month-to-month,1
8,28,25-48 months,104.80,1257.6,Month-to-month,1
9,62,49-72 months,56.15,673.8,One year,0

**=> checking for null values**

In [42]:
df[
    [
        "AnnualCharges",
        "TenureGroup",
        "IsMonthToMonth"
    ]
].isnull().sum()

AnnualCharges     0
TenureGroup       0
IsMonthToMonth    0
dtype: int64

**=> checking data types**

In [45]:
df[["AnnualCharges", "TenureGroup", "IsMonthToMonth"]].info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   AnnualCharges   7043 non-null   float64
 1   TenureGroup     7043 non-null   category
 2   IsMonthToMonth  7043 non-null   int64
dtypes: category(1), float64(1), int64(1)
memory usage: 117.3 KB

**=> saving data set containing added features**

In [46]:
df.to_csv(
    "../data/processed/telco_customer_churn_features.csv",
    index=False
)

In [47]:
pd.read_csv(
    "../data/processed/telco_customer_churn_features.csv"
).head()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,LTV,AnnualCharges,TenureGroup,IsMonthToMonth
0,7590-VHVEG,Female,No,Yes,No,1,No,No phone service,DSL,No,...,Month-to-month,Yes,Electronic check,29.85,29.85,No,29.85,358.2,0-12 months,1
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,...,One year,No,Mailed check,56.95,1889.50,No,1936.30,683.4,25-48 months,0
2,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,107.70,646.2,0-12 months,1
3,7795-CFOCW,Male,No,No,No,45,No,No phone service,DSL,Yes,...,One year,No,Bank transfer (automatic),42.30,1840.75,No,1903.50,507.6,25-48 months,0
4,9237-HQITU,Female,No,No,No,2,Yes,No,Fiber optic,No,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,141.40,848.4,0-12 months,1